### ISSUE TITLE
Matching elements of a collection using object graph comparisons

### ISSUE THREAD

**Issue by james-ecargo** [fluentassertions/fluentassertions#790] opened 2018-03-01 20:20 UTC
I've found the `ShouldBeEquivalentTo` method's object graph comparisons to be very helpful however there are certain situations where I'd like to this kind of matching with other methods.

For example in the following I want to assert that the collection at least contains this object:
```
MenuItem[] menuItems = page.GetNavigationMenuItems();

// Assert
menuItems
    .ElementAt(2)
    .ShouldBeEquivalentTo(
        new MenuItem(
            "Home",
            Optional.Empty<string>(),
            new[]
            {
                new MenuItem(
                    "Profile",
                    Optional.Create("/Home/Profile")
                ),
                new MenuItem(
                    "Blog",
                    Optional.Create("/Home/Blog")
                ),
                new MenuItem(
                    "News",
                    Optional.Create("/Home/News")
                )
            }
        ));
```

Here I've used `ElementAt(2)` however in an ideal world I'd like to be able to use the `Contains` method.
I don't necessarily want to constrained by the ordering of the collection. 

```
menuElements.Contains(...)
```

Is there a way that I can achieve this using FA at the moment?
If not would a method like `ContainsEquivalentOf(...)` be useful?

**Comment by dennisdoomen** [comment] 2018-03-01 20:26
Duplicate of #699

**Closed by dennisdoomen** 2018-03-01 20:26 UTC
