### ISSUE TITLE
System.ArgumentOutOfRangeException: 'Length cannot be less than zero. on boolean check

### ISSUE THREAD

**Issue by rakirs2** [fluentassertions/fluentassertions#2410] opened 2023-10-27 00:58 UTC
### Description

Getting this issue on a true false test when it shoul

### Reproduction Steps

prod
```csharp
static internal bool foo(){};
```

test
```csharp
foo().ShouldBe.False()
```

### Expected behavior

When returning true on a boolean that's expecting  false, I expect "was expecting false but recieved true-- not a length check"

### Actual behavior

System.ArgumentOutOfRangeException: 'Length cannot be less than zero. on boolean check

### Are you willing to help with a pull-request?

No

**Comment by IT-VBFK** [comment] 2023-10-27 07:43
I cannot reproduce this.. could you add a _complete_ test case?

**Comment by dennisdoomen** [comment] 2023-10-28 07:27
I'm sorry, but if you're not even willing to fill in the required fields, then we'll close the issue.

**Closed by dennisdoomen** 2023-10-28 07:27 UTC
Labels: bug, requires-clarification, triage
