### ISSUE TITLE
CollectionAssertions.ByEquivalentTo fails with StackOverflowException

### ISSUE THREAD

**Issue by AlexanderSher** [fluentassertions/fluentassertions#880] opened 2018-07-30 22:55 UTC
### Description

For the instance of type `C : IEnumerable<C>` that returns itself in the enumeration, `ByEquivalentTo` causes `StackOverflowException`

### Complete minimal example reproducing the issue

```csharp
[TestClass]
public class UnitTest1 {
    [TestMethod]
    public void TestMethod1() {
        var t1 = new C();
        var t2 = new C();
        var set = new HashSet<C>{t1, t2};
        set.Should().BeEquivalentTo(t2, t1);
    }

    public class C : IEnumerable<C> {
        public IEnumerator<C> GetEnumerator() {
            yield return this;
        }

        IEnumerator IEnumerable.GetEnumerator() {
            return GetEnumerator();
        }
    }
}
```

### Expected behavior:

Test passes

### Actual behavior:

Test runner crashes with `StackOverflowException`

### Versions

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="5.4.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.7.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="1.2.1" />
    <PackageReference Include="MSTest.TestFramework" Version="1.2.1" />
  </ItemGroup>
</Project>
```

### Additional Information

FluentAssertions version 4.19.4 doesn't have this issue.

**Comment by dennisdoomen** [comment] 2018-08-09 19:52
After the #887 fix is merged your particular example will succeed simply because the subject and expectation refer to the same instance of `C`. To reproduce the cyclic detection problem, you would have to change the assertion to 

`set.Should().BeEquivalentTo(new C(), new C());`

**Closed** 2018-08-12 17:30 UTC
Labels: bug
