### ISSUE TITLE
Variable name is not displayed after await assertion

### ISSUE THREAD

**Issue by hongcc1** [fluentassertions/fluentassertions#1755] opened 2021-12-12 04:06 UTC
### Description

It is found that the variable names will not be included in the assertion message when the assertion comes after the await assertion such as `NotThrowAsync()` and `CompleteWithinAsync()`. 

### Complete minimal example reproducing the issue

```csharp
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Threading.Tasks;
using FluentAssertions;
using FluentAssertions.Extensions;

namespace MyUnitTests
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public async Task RunAsyncAssertion()
        {
            // Arrange and Act
            string someText = "Hello";
            Func<Task> myTask = () => Task.Delay(1.Seconds());

            // Assert
            await myTask.Should().CompleteWithinAsync(2.Seconds());
            someText.Should().Be("Hi");
        }
    }
}

```

### Expected behavior:

Assertion failure should be something like `Expected someText to be "Hi" with a length of 2, but "Hello" has a length of 5, differs near "ell" (index 1).`

### Actual behavior:

`Expected string to be "Hi" with a length of 2, but "Hello" has a length of 5, differs near "ell" (index 1).`
Note that `string` is displayed instead of the variable name `someText`. 

This is not caused by the `await` keyword used. If the Fluent async assertion is not used, the variable name can be displayed correctly. Example:

```csharp
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Threading.Tasks;
using FluentAssertions;
using FluentAssertions.Extensions;

namespace MyUnitTests
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public async Task RunAsyncAssertion()
        {
            // Arrange and Act
            string someText = "Hello";
            Func<Task> myTask = () => Task.Delay(1.Seconds());

            // Assert
            await myTask.Invoke();
            someText.Should().Be("Hi");
        }
    }
}

```
Result:
`Expected someText to be "Hi" with a length of 2, but "Hello" has a length of 5, differs near "ell" (index 1).`

### Versions

* Fluent Assertions 6.2.0
* .NET framework 4.7.2

### Additional Information

This is my first time submitting an issue on GitHub. Hope it's alright. 😅

**Comment by dennisdoomen** [comment] 2021-12-13 06:42
Thank you for taking the time to report this. Are your unit tests compiled in debug mode when you execute them?

**Comment by hongcc1** [comment] 2021-12-13 07:17
Hi @dennisdoomen 

You are welcome. 
I was compiled in debug mode. Just now I tried again in release mode, it still has the same observation.

**Comment by dennisdoomen** [comment] 2021-12-13 07:30
No, it _should_ be compiled in debug mode. So that confirms it's an actual bug in FA.

**Comment by hongcc1** [comment] 2021-12-13 09:43
![image](https://user-images.githubusercontent.com/46660638/145788195-056b4fc4-8724-4bd7-bb15-6b9673cc6a67.png)
Hi @dennisdoomen. Alright. Probably I understood differently. 
Just FYI, the above screenshot is showing I compile in Release mode, and then run the test by Ctrl R + T. The result message results `string` instead of `someText`.

**Comment by dennisdoomen** [comment] 2021-12-13 15:16
And if you run the test in debug mode? 

BTW: We typically have a release solution config where only the tests use a debug configuration. Everything else is still compiled to release.

**Comment by dennisdoomen** [comment] 2021-12-13 19:15
You misunderstood me. I was talking about your unit test project.

**Comment by hongcc1** [comment] 2021-12-14 00:01
Thanks for clarifying. Yes, I observe the bug in debug and release mode.

**Comment by jnyrup** [comment] 2021-12-28 15:50
I can confirm this issue.

The problem is how we search the stack traces of MSTest and xUnit.
In `CallerIdentifier.DetermineCallerIdentity` `firstFluentAssertionsCodeIndex` is incorrectly computed for MSTest, which makes us skip the stack frame of the test method and miss the chance of determining the caller identifier.

**Comment by MullerWasHere** [comment] 2022-01-04 14:14
I created a sample test in TaskAssertionSpecs.cs to demonstrate this issue in xUnit as well:
```
[UIFact]
public async Task When_resolving_async_to_main_thread_variable_name_used_for_assertion_should_be_detected()
{
    // Arrange
    const string someText = "Hello";
    Func<Task> task = () => Task.Delay(1.Seconds());

    // Act
    await task.Should().CompleteWithinAsync(2.Seconds());
    Action act = () => someText.Should().Be("Hi");

    // Assert
    act.Should().Throw<XunitException>()
        .WithMessage("Expected someText to be \"Hi\" with a length of 2, but \"Hello\" has a length of 5, differs near \"ell\" (index 1).");
}
```

I wrote a simple fix for this issue in `DetermineCallerIdentity()`:
```
public static string DetermineCallerIdentity()
{
    string caller = null;

    try
    {
        var stack = new StackTrace(fNeedFileInfo: true);

        var allStackFrames = stack.GetFrames()
            .Where(frame => !IsCompilerServices(frame))
            .ToArray();

        int searchStart = allStackFrames.Length - 1;

        if (StartStackSearchAfterStackFrame.Value is not null)
        {
            searchStart = Array.FindLastIndex(
                allStackFrames,
                allStackFrames.Length - StartStackSearchAfterStackFrame.Value.SkipStackFrameCount,
                frame => !IsCurrentAssembly(frame));
        }

        int lastUserStackFrameBeforeFluentAssertionsCodeIndex = allStackFrames
            .Select((frame, index) => new { frame, index = index + 1 })
            .Take(searchStart + 1)
            .FirstOrDefault(pair => !IsCurrentAssembly(pair.frame) &&
                           !IsDotNet(pair.frame))?.index - 1 ?? 0;

        for (int i = lastUserStackFrameBeforeFluentAssertionsCodeIndex; i < allStackFrames.Length; i++)
        {
            var frame = allStackFrames[i];

            Logger(frame.ToString());

            if (frame.GetMethod() is not null
                && !IsDynamic(frame)
                && !IsDotNet(frame)
                && !IsCustomAssertion(frame))
            {
                caller = ExtractVariableNameFrom(frame);
                break;
            }
        }
    }
    catch (Exception e)
    {
        // Ignore exceptions, as determination of caller identity is only a nice-to-have
        Logger(e.ToString());
    }

    return caller;
}
```

Now it finds the first index where it isn't the current assembly and isn't a dotNet call. In the case of a stack with async code not resolved, this should work fine since the search starts from the top of the stack. This also works fine in case `StartStackSearchAfterStackFrame.Value` is not null. All tests are passing but some refactoring could definitely take place here.

What do you think?

**Comment by jnyrup** [comment] 2022-01-06 19:01
@MullerWasHere Thanks for looking into this, much appreciated!
I see that we cannot search from the bottom of the stack as "unknowns", here `Xunit.StaFact`, can hook into the test framework, which seems hard (if not impossible?) to distinguish from a test class.

Are you interested in creating a PR for this?

While understanding your solution, I tried to simplify the example and code a bit more.

```cs
[UIFact]
public async Task When_resolving_async_to_main_thread_variable_name_used_for_assertion_should_be_detected()
{
    // Arrange
    const string someText = "Hello";
    Func<Task> task = async () => await Task.Yield();

    // Act
    await task.Should().NotThrowAsync();
    Action act = () => someText.Should().Be("Hi");

    // Assert
    act.Should().Throw<XunitException>()
        .WithMessage("*someText*", "it should capture the variable name");
}
```

```cs
int lastUserStackFrameBeforeFluentAssertionsCodeIndex = Array.FindIndex(
    allStackFrames,
    startIndex: 0,
    count: searchStart + 1,
    frame => !IsCurrentAssembly(frame) && !IsDotNet(frame));
```

**Comment by MullerWasHere** [comment] 2022-01-06 22:35
@jnyrup I'd love to create a PR for it! Also, thanks for the suggestions.

**Closed** 2022-01-11 06:52 UTC
Labels: bug, up-for-grabs
