### ISSUE TITLE
Change context when using Which

### ISSUE THREAD

**Issue by cmeeren** [fluentassertions/fluentassertions#2223] opened 2023-06-16 08:50 UTC
### Description

When using `Which` (and possibly other parts of the API that transform the value), the context should be changed so the messages make sense.

### Reproduction Steps

```f#
let foo = seq { yield "asd" }
foo.Should().ContainMatch("asd", "").Which.Length.Should().Be(0, "") |> ignore
```

### Expected behavior

Failing with a message like this (does not need to be exactly this):

> Expected foo.Length to be 0, but found 3 (difference of 3).

### Actual behavior

Fails with this message:

> Expected foo to be 0, but found 3 (difference of 3).

This is misleading, because `foo` should not be `3`. It is the `Length` of `foo` that should be `3`.

**Comment by cmeeren** [comment] 2023-06-16 09:09
It would also be nice to have an API for this to use for custom assertions. For example, I have the following extension to `ReferenceTypeAssertions` that allows me to transform the value before asserting further:

```f#
    type ReferenceTypeAssertions<'TSubject, 'TAssertions
        when 'TAssertions :> ReferenceTypeAssertions<'TSubject, 'TAssertions>> with

        member this.WhenTransformed(f: 'TSubject -> 'TTransformed) = f this.Subject
```

This allows me to do this:

```f#
result
    .Should()
    .MatchRegex("^\d{6}-\d{4}$", "the value should be formatted correctly")
    .And.WhenTransformed(String.replace "-" "")
    .Should()
    .Be(orgNo, "the value should be equal to the input ignoring spaces")
```

However, if the last one fails, it still uses the variable name `result` as the context.

I know I can override the context using `AssertionScope`, but I can't use that in `WhenTransformed` because I don't actually assert anything there.

Another example is a custom assertions type `OptionAssertions` I have made to assert (using a method `BeSome` an F# `option` value to be `Some _` and when use `Which` to continue asserting on the inner value. I can't use `AssertionScope` because it's only relevant for everything that uses the `AndWhichConstraint` that is returned in `BeSome`.

**Comment by dennisdoomen** [comment] 2023-06-16 12:36
> It would also be nice to have an API for this to use for custom assertions. For example, I have the following extension to ReferenceTypeAssertions that allows me to transform the value before asserting further:

Would you mind to make that a separate feature request?

**Comment by cmeeren** [comment] 2023-06-16 12:49
#2224

**Comment by cmeeren** [comment] 2023-07-15 15:19
For what it's worth, I am no longer interested in this. As detailed in https://github.com/fluentassertions/fluentassertions/issues/2225#issuecomment-1636796736, I am creating a brand new F# assertions library inspired by FluentAssertions. That library will automatically support this feature with no end user hassle. Feel free to close.

**Comment by dennisdoomen** [comment] 2023-08-12 11:28
Duplicate of #1502

**Closed by dennisdoomen** 2023-08-12 11:28 UTC
Labels: bug, triage
