### ISSUE TITLE
ThrowsAsync and ThrowsExactlyAsync do not fail the test when it is not awaited

### ISSUE THREAD

**Issue by chadlevn** [fluentassertions/fluentassertions#1766] opened 2022-01-04 21:19 UTC
### Description

ThrowsExactlyAsync doesn't fail a test when it is not awaited.

### Complete minimal example reproducing the issue
E.g.

```csharp
[Fact]
public void NotAwaited_ThrowsException()
{
    FluentActions.Invoking(() => TestMethodAsync()).Should().ThrowExactlyAsync<NullReferenceException>();
}

private async Task TestMethodAsync()
{
    throw new NotImplementedException();
}
```

### Expected behavior:

Changing the above to the following results in a failed test.
```csharp
[Fact]
public async Task NotAwaited_ThrowsException()
{
    await FluentActions.Invoking(() => TestMethodAsync()).Should().ThrowExactlyAsync<NullReferenceException>();
}
```

### Actual behavior:

Tests pass when they shouldn't.

### Versions

6.3.0

### Additional Information

Adding a utility to force synchronized execution results in the test failing as expected. Something like this;
```csharp
public static ExceptionAssertions<TException> AssertAsyncMethodThrowsExactlyAsync<TException>(Task method) where TException : Exception =>
     FluentActions.Awaiting(() => method).Should().ThrowExactlyAsync<TException>().Result;
```

I'm not sure what can actually be done about this but it's just something I've noticed. Ideally I'd like to see a warning or compile error if possible.

**Comment by dennisdoomen** [comment] 2022-01-05 08:49
Hi,

This is by design and the result of how the C# compiler works. But when I remove the `await`, the compiler gives me `CS4014` and `CS1998` errors. 

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/572734/148188138-565215b5-6feb-4d41-8efc-5c24fa44d909.png">

Either way, this is not a problem of FluentAssertions, so I'm closing the issue.

**Closed by dennisdoomen** 2022-01-05 08:49 UTC

**Comment by jnyrup** [comment] 2022-01-05 09:46
See #1746 for a discussion on how to get more compiler errors for this

**Comment by dennisdoomen** [comment] 2022-01-05 18:11
Or read https://www.continuousimprover.com/2022/01/awaiting-the-awaitable
