### ISSUE TITLE
BeEquivalentTo For().Exclude() does not work for comparison of collections

### ISSUE THREAD

**Issue by abartho** [fluentassertions/fluentassertions#1989] opened 2022-09-06 12:54 UTC
### Description

I have an array or list of nested objects that I would like to check for equivalency. The child objects have some properties that I would like to exclude from the comparison. I'm using the new For().Exclude() syntax. That works fine when comparing individual objects, but it fails when comparing collections.

### Complete minimal example reproducing the issue

```csharp
using FluentAssertions;

public class ForExcludeTest
{
    [Fact]
    public void Test()
    {
        var actualContainer = new Container
        {
            Children = new[]
            {
                new Child
                {
                    ChildId = 20,
                    Name = "Child20"
                }
            }
        };

        var expectedContainer = new Container
        {
            Children = new[]
            {
                new Child
                {
                    ChildId = 20
                }
            }
        };

        // Comparing the actual objects works
        actualContainer.Should().BeEquivalentTo(expectedContainer,
            options => options
                .For(o => o.Children).Exclude(o => o.Name)
            );

        // Comparing the objects inside a list fails
        new List<Container> { actualContainer }.Should().BeEquivalentTo(new List<Container> { expectedContainer },
            options => options
                .For(o => o.Children).Exclude(o => o.Name)
            );
    }

    public class Container
    {
        public Child[] Children { get; set; }
    }

    public class Child
    {
        public int ChildId { get; set; }
        public string Name { get; set; }
    }
}
```

### Expected behavior:

Both assertions should succeed.

### Actual behavior:

The second assertion (on a list) fails with the following error:
```
Expected property root[0].Children[0].Name to be <null>, but found "Child20".

With configuration:
- Use declared types and members
- Compare enums by value
- Compare tuples by their properties
- Compare anonymous types by their properties
- Compare records by their members
- Include non-browsable members
- Include all non-private properties
- Include all non-private fields
- Exclude member Children[]Name
- Match member by name (or throw)
- Be strict about the order of items in byte arrays
- Without automatic conversion.


  Stack Trace: 
XUnit2TestFramework.Throw(String message)
TestFrameworkProvider.Throw(String message)
CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context)
EquivalencyValidator.AssertEquality(Comparands comparands, EquivalencyValidationContext context)
GenericCollectionAssertions`3.BeEquivalentTo[TExpectation](IEnumerable`1 expectation, Func`2 config, String because, Object[] becauseArgs)
ForExcludeTest.Test() line 38
```

### Versions

* FluentAssertions 6.7.0
* .NET 6.0

**Comment by IT-VBFK** [comment] 2022-09-06 19:07
Possible duplicate of #1919

**Comment by alexcristd** [comment] 2022-10-17 07:24
I'm facing the same issue. I don't see it as a duplicate of #1919, but as a possible bug of the new syntax.

**Comment by jkalmeij** [comment] 2022-11-07 13:35
I am also facing this issue on FluentAssertions 6.8.0.

I worked around it by defining the following class:

```csharp
        /// <summary>
        /// Work-around for "BeEquivalentTo For().Exclude() does not work for comparison of collections"
        /// https://github.com/fluentassertions/fluentassertions/issues/1989
        /// </summary>
        private class FluentAssertionsIssue1989Workaround
        {
            public FluentAssertionsIssue1989Workaround(List<Container> workaround)
            {
                Workaround = workaround;
            }

            public List<Container> Workaround { get; set; }
        }
```

and then modifying the assertion:

```csharp
        new FluentAssertionsIssue1989Workaround(new List<Container> { actualContainer }).Should().BeEquivalentTo(new FluentAssertionsIssue1989Workaround(new List<Container> { expectedContainer }),
            options => options
                .For(o => o.Workaround)
                .For(o => o.Children).Exclude(o => o.Name)
            );
```

**Comment by whymatter** [comment] 2023-03-03 08:25
@dennisdoomen We discovered that issue yesterday. I would like to add that this problem does not only affect the `For().Exclude()` syntax, but also the `.Excluding()` (and probably `Including` as well)

Since you added the bug label. I offer to look into this.

**Comment by dennisdoomen** [comment] 2023-03-03 08:27
> Since you added the bug label. I offer to look into this.

Sure. Go ahead.

**Comment by whymatter** [comment] 2023-03-03 08:28
> I'm facing the same issue. I don't see it as a duplicate of #1919, but as a possible bug of the new syntax.

As in my previous comment: It is a duplicate/extension of #1919 since the new syntax is not the cause. So Goal is to fix #1919 as well

**Comment by dennisdoomen** [comment] 2023-03-04 08:25
Hmm, in #1919 the issue is that the problem happens if the root is a collection. And the example in this issue is not using a root collection. So let's keep this one open until we've fixed #1919.

**Comment by whymatter** [comment] 2023-03-04 12:39
Mmh, I respectfully disagree. The root in this issue is indeed a collection:

See the description:
> I have an array or list of nested objects that I would like to check for equivalency

And the code example:
```c#
// Comparing the objects inside a list fails
new List<Container> { actualContainer }.Should().BeEquivalentTo(new List<Container> { expectedContainer },
    options => options
        .For(o => o.Children).Exclude(o => o.Name)
    );
```

Or is there anything I am missing?

**Comment by abartho** [comment] 2023-03-04 13:27
I agree with @whymatter .

**Closed** 2023-04-01 11:21 UTC
Labels: bug
