### ISSUE TITLE
Add dependency on System.Xml.Linq

### ISSUE THREAD

**Issue by abatishchev** [fluentassertions/fluentassertions#79] opened 2014-03-12 05:25 UTC
Currently FluentAssertions.dll is tightly dependent on System.Xml.Linq.dll. Its unreferencing causes a compiler error:

```
The type 'XDocument' is required here and is unavailable. You must add a reference to assembly 'System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```

Please consider re-designing to remove such necessity..

**Comment by comecme** [comment] 2019-12-13 13:47
If FluentAssertions has this dependency, why doesn't the NuGet-package show this as a dependency?

**Comment by dennisdoomen** [comment] 2019-12-13 15:47
It's something from the past.

**Comment by comecme** [comment] 2019-12-13 17:14
What do you mean? 
1. It the need for System.Xml.Linq something from the past?
2. It the fact that the dependencies is not present in the NuGet package from the past?

I created a new Unit Test Project (.NET Framework) in VS2019, added FluentAssertions, and tried to use it, but I had to manually add System.Xml.Linq using NuGet Package Manager.

Ah, but if I create a new MSTest Test Project (.NET Core) I do not have to ad System.Xml.Linq. I suppose that is what you mean by "something from the past" then.

I think the NuGet package should have a dependency on System.Xml.Linq for its .NETFramework v4.7 and v4.5 targets.

**Comment by dennisdoomen** [comment] 2019-12-15 16:30
Yeah, you're right. Somehow we lost that dependency.

**Comment by comecme** [comment] 2019-12-15 19:03
Thanks for reopening the issue, but technically, the issue I mentioned is not the same as this issue. You still won't remove the dependency on System.Xml.Linq, but you will (re)add it to the package.

**Comment by dennisdoomen** [comment] 2019-12-17 10:58
You're right @comecme.

**Comment by FlavioGoncalves-Cayas** [comment] 2019-12-20 12:04
Version 5.6.0 seems to be the most recent version, which includes the dependency on System.Xml.Linq. So downgrading is a temporary solution.

**Comment by comecme** [comment] 2019-12-20 17:39
I don't understand what you mean. Version 5.6.0 is not the most recent version (5.9.0 is the most recent). Also, version 5.6.0 only has no dependencies for .NETFramework,Version=v4.7.

**Comment by jnyrup** [comment] 2019-12-20 18:18
I'm the offender #1009 .

**Comment by julealgon** [comment] 2019-12-31 16:09
Noticed this problem while creating a few brand new projects on the full framework. We have this habit of sending a commit for the project creation, and then adding the tests later. Immediately when trying to add the tests, we'd be hit with the requirement to then add `System.Xml` and `System.Xml.Linq`.

What's the status on this one?

I tend to agree with @abatishchev and would prefer a separate `FluentAssertions.Xml` package here, and then remove the dependency on the main one. These libraries should be as clean as possible in regards to their dependencies.

**Comment by dennisdoomen** [comment] 2020-01-01 17:59
This has been fixed on `master` just a minute ago.

**Comment by comecme** [comment] 2020-02-05 18:53
I did not have time to try it yet, but it does not seem to be fixed. Or not completely.

If I install version 5.10.0 into a .NET 4.7.1 Framework unit test project, no dependencies are installed. 

When I use `Should()` I no longer get a message telling me I need to reference System.Xml.Linq. So far so good...

But I _do_ get a message telling me I need to install System.Xml.

```
CS0012	The type 'XmlNode' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```

**Comment by dennisdoomen** [comment] 2020-02-06 09:19
Ah, so we also need to add `System.Xml` as well.

**Comment by dennisdoomen** [comment] 2020-02-09 13:00
Fixed in 5.10.1

**Closed by dennisdoomen** 2020-02-09 13:00 UTC
Labels: bug

**Comment by braydie** [comment] 2022-09-22 08:10
Hey, I encountered this issue in v6 - I've downgraded to 5.10.3 and it seems to be working OK for me now

**Comment by dennisdoomen** [comment] 2022-09-22 17:59
> Hey, I encountered this issue in v6 - I've downgraded to 5.10.3 and it seems to be working OK for me now

Why would you downgrade? You can always add the missing dependency. Is there any?

**Comment by harvzor** [comment] 2022-11-29 15:58
Discovered this issue on version 6.6.0 and 6.8.0. The error is:

```
The type 'XDocument' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Xml.XDocument, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

My project is using dotnet 6.0.

Strange that it's asking me to use System.Xml.XDocument v6.0.0 as the latest version is 4.3.0 https://www.nuget.org/packages/System.Xml.XDocument/ 😅

**Comment by jnyrup** [comment] 2022-11-29 16:06
@harvzor Can you share your `.csproj` file or even better a minimal `csproj` reproducing this?

It sounds a bit like an outdated nuget package manager or IDE that does not correctly know about `net6` (the one released ~1 year ago) and thinks is some .net framework 6.0 (which does not exists.)
