### ISSUE TITLE
FormatException when asserting on the content of an exception message (using WithMessage(string)) when the expected exception message contains braces ({})

### ISSUE THREAD

**Issue by Sergeus** [fluentassertions/fluentassertions#586] opened 2017-07-16 16:17 UTC
I'm using the latest (at time of writing) NuGet package distribution in VS2013: Id FluentAssertions, Version 4.19.3. 

I'm writing an extension method for the `GenericCollectionAssertions<T>` class and tests to go along with my new extension.   The extension is partially implemented, like so:

```C#
public static AndConstraint<GenericCollectionAssertions<T>> ContainSingleItemOfType<T>(this GenericCollectionAssertions<T> assertions, Type type, string reason = "", params object[] reasonArgs)
{
	var itemsOfType = assertions.Subject.Where(i => type.IsAssignableFrom(i.GetType()));

	Execute.Assertion
		.ForCondition(itemsOfType.Any())
		.BecauseOf(reason, reasonArgs)
		.FailWith("Expected collection {0} to contain a single item of type {1}{reason}, but it was empty.", assertions.Subject, type);

	throw new NotImplementedException();
}
```

The test looks like this:

```C#
[Test]
public void ContainSingleItemOfType_EmptyCollection_Throws()
{
	var collection = Enumerable.Empty<object>();

	Action assert = () => collection.Should().ContainSingleItemOfType(typeof(ICloneable));

	assert.ShouldThrow<AssertionException>()
		.WithMessage(@"Expected collection {empty} to contain a single item of type ICloneable, but it was empty.");
}
```

Debugging the test, the assertion does throw the `AssertionException` with the expected message.(`"Expected collection {empty} to contain a single item of type System.ICloneable, but it was empty."`)   However, `WithMessage` subsequently throws a `FormatException`, which fails my test. (This `FormatException` comes from line 66 of `MessageBuilder.cs`, according to the debugger.)

Am I missing some level of formatting that I should be doing in my test or in my assertion?   If I change my assertion message and test to look for a message that *doesn't* contain braces, then it all works fine:

```C#
public static AndConstraint<GenericCollectionAssertions<T>> ContainSingleItemOfType<T>(this GenericCollectionAssertions<T> assertions, Type type, string reason = "", params object[] reasonArgs)
{
	var itemsOfType = assertions.Subject.Where(i => type.IsAssignableFrom(i.GetType()));

	Execute.Assertion
		.ForCondition(itemsOfType.Any())
		.BecauseOf(reason, reasonArgs)
		.FailWith("Expected the collection to contain a single item of type {0}{reason}, but it was empty.", type);

	throw new NotImplementedException();
}
```
```C#
[Test]
public void ContainSingleItemOfType_EmptyCollection_Throws()
{
	var collection = Enumerable.Empty<object>();

	Action assert = () => collection.Should().ContainSingleItemOfType(typeof(ICloneable));

	assert.ShouldThrow<AssertionException>()
		.WithMessage(@"Expected the collection to contain a single item of type System.ICloneable, but it was empty.");
}
```

I'm thinking it could be an issue with `WithMessage` itself?

**Comment by Sergeus** [comment] 2017-07-16 16:42
It's worth noting that I see this behavior if *either* the actual message thrown by the assertion or the expected message passed into `WithMessage` contain braces, not just when both do.

**Comment by dennisdoomen** [comment] 2017-07-16 17:05
Those braces have cost me some issues over the years. Why are you passing `{empty}` into `WithMessage` even though you don't have have a variable like that.

**Comment by Sergeus** [comment] 2017-07-16 17:44
I'm expecting the exception message thrown by my assertion to contain `{empty}` within the message.   That's because I'm asserting on an empty collection (the variable `collection` in the test, which is the subject of the assertion being tested, is initialized to be an empty enumerable), similar to the exception messages you get back from `GenericCollectionAssertions<T>.Contains`. 

The actual value `{empty}` comes from the default `ValueFormatter` for enumerables.   I'm passing `assertions.Subject` (which is an `IEnumerable<T>`) into the call to `FailWith` in the assertion itself.

**Comment by dennisdoomen** [comment] 2017-07-16 17:54
Hmm, try removing the `$` at the beginning and retry.

**Comment by Sergeus** [comment] 2017-07-16 18:08
You mean the `@` before the string?   I've tried removing that, but the behavior remains the same.

Actually, there is an additional wrinkle to this, that I've found now going back to try out your suggestion.   In my expected message, I had mistakenly omitted the `System.` from the beginning of `System.ICloneable`.   If I correct my expected message, then the test passes.   

But if I change my expected message so that it is wrong, I get a `FormatException` instead of an `AssertionException`.  I would expect to get an `AssertionException` telling me that the message doesn't match the expected value.

**Comment by Sergeus** [comment] 2017-07-16 18:08
Woops, didn't mean to close!

**Comment by dennisdoomen** [comment] 2017-07-16 18:26
I agree. Will have to investigate this. If you want, you can try to do that yourself and provide me with a PR. Even a PR of a failing test would help me tremendously.

**Comment by Sergeus** [comment] 2017-07-16 19:56
Cool, I'll see what I can do!

**Comment by ojamte** [comment] 2017-12-01 10:27
Many times I print out an objects values in its overridden `ToString()`. To be able to list many properties with objects and lists, I sometimes uses a json-like string to present to values.
When I do so and show this text in a "because" string, I get an `System.FormatException` from **FluentAssertions**.

These few lines of code throws that exception:

```
var anErrorDescriptionWithJsonStyle = "becasue this json-data {\r\n  \"firstName\": \"John\"\r\n  \"lastName\": \"Doe\"\r\n}";
var expected = "expected";
var actual = "actual";

actual.Should().Be(expected, anErrorDescriptionWithJsonStyle);
```

Since I am not sending any `params object[] becauseArgs`, would it be possible for **FluentAssertions** to not call `String.Format`?

@Sergeus , have you done anything more about this, like an failing test or a PR?

**Comment by dennisdoomen** [comment] 2017-12-01 11:00
@ojamte which version?

**Comment by ojamte** [comment] 2017-12-01 11:32
Sorry, 4.19.4 from nuget.

**Comment by jnyrup** [comment] 2017-12-28 20:56
@ojamte 
Can you provide a real life example that triggers the exception?

I tried to reproduce your case using FluentAssertions 4.19.4 by defining a class `JsonToString` as follows:

```csharp
private class JsonToString
{
	public override string ToString()
	{
		return "{\r\n  \"firstName\": \"John\"\r\n  \"lastName\": \"Doe\"\r\n}";
	}
}
```

Both the tests below passed, no matter if I specified `becauseArgs` or not.

```csharp
[Fact]
public void When_ToString_contains_braces_and_no_becauseArgs_are_specified_it_should_not_fail_in_formatting()
{
	//-----------------------------------------------------------------------------------------------------------
	// Arrange
	//-----------------------------------------------------------------------------------------------------------
	JsonToString actual = new JsonToString();

	//-----------------------------------------------------------------------------------------------------------
	// Act
	//-----------------------------------------------------------------------------------------------------------
	Action act = () => actual.Should().BeNull("this is json");

	//-----------------------------------------------------------------------------------------------------------
	// Assert
	//-----------------------------------------------------------------------------------------------------------
	act.ShouldThrow<XunitException>()
		.WithMessage("*John*");
}

[Fact]
public void When_ToString_contains_braces_it_should_not_fail_in_formatting()
{
	//-----------------------------------------------------------------------------------------------------------
	// Arrange
	//-----------------------------------------------------------------------------------------------------------
	JsonToString actual = new JsonToString();

	//-----------------------------------------------------------------------------------------------------------
	// Act
	//-----------------------------------------------------------------------------------------------------------
	Action act = () => actual.Should().BeNull("this is json {0}", "lol");

	//-----------------------------------------------------------------------------------------------------------
	// Assert
	//-----------------------------------------------------------------------------------------------------------
	act.ShouldThrow<XunitException>()
		.WithMessage("*John*");
}
```

**Comment by ojamte** [comment] 2017-12-29 12:17
Change this line:
`Action act = () => actual.Should().BeNull("this is json {0}", "lol");
`
To:
`Action act = () => actual.Should().BeNull(actual.ToString());`

**Comment by ojamte** [comment] 2017-12-29 12:32
It could possibly be solved something like this:
```
public AssertionScope BecauseOf(string because, params object[] becauseArgs)
{
    if (because == null)
    {
        reason = string.Empty;
        return this;
    }

    if (becauseArgs == null || becauseArgs.Length == 0)
    {
        reason = because;
        return this;
    }

    reason = string.Format(because, becauseArgs);
    return this;
} 
```

But I haven't been able to study all the code to see if this match other parts of the library or if it could have some other implications.

**Comment by ojamte** [comment] 2017-12-29 12:46
Or perhaps this is more readable not as error prone with just one return.

```
public AssertionScope BecauseOf(string because, params object[] becauseArgs)
{
    if (string.IsNullOrEmpty(because))
    {
        reason = string.Empty;
    }
    else if (becauseArgs == null || becauseArgs.Length == 0)
    {
        reason = because;
    }
    else
    {
        reason = string.Format(because, becauseArgs);
    }
    return this;
}
```

**Comment by jnyrup** [comment] 2017-12-29 13:06
@ojamte I tried to do exactly this and it does resolve your particular example.

Unfortunately it does not solve the problem in general.

Take this example, where a the `because` message contains  `{0}` which should be replaced with `"this"` and I forgot to pass `becauseArgs` to `BeNull`.

```csharp
//-----------------------------------------------------------------------------------------------------------
// Arrange
//-----------------------------------------------------------------------------------------------------------
string anErrorDescriptionWithJsonStyle = "I want {0} to be replaced";
string becauseArgs = "this";
string actual = "actual";

//-----------------------------------------------------------------------------------------------------------
// Act
//-----------------------------------------------------------------------------------------------------------
Action act = () => actual.Should().BeNull(anErrorDescriptionWithJsonStyle);

//-----------------------------------------------------------------------------------------------------------
// Assert
//-----------------------------------------------------------------------------------------------------------
act.ShouldThrow<XunitException>();
```

Currently `string.Format` throws a `FormatException` as I forgot to pass in `becauseArgs`.
Not calling `string.Format` when `becauseArgs` is null or empty would hide this exception.

---

The general problem is that the json is not a valid format string and when blended into the general because string without any escaping, it cannot easily be distinguished.

I would do as follows:

Define an escape extension like 

```
public static class StringExtensions
{
	public static string Escape(this string str) => str.Replace("{", "{{").Replace("}", "}}");
}
```

And then escape the json string before merging with the `because` string.
```
//-----------------------------------------------------------------------------------------------------------
// Arrange
//-----------------------------------------------------------------------------------------------------------
string json = "{\r\n  \"firstName\": \"John\"\r\n  \"lastName\": \"Doe\"\r\n}";
string anErrorDescriptionWithJsonStyle = "becasue this json-data " + json.Escape();
string actual = "actual";

//-----------------------------------------------------------------------------------------------------------
// Act
//-----------------------------------------------------------------------------------------------------------
Action act = () => actual.Should().BeNull(anErrorDescriptionWithJsonStyle);

//-----------------------------------------------------------------------------------------------------------
// Assert
//-----------------------------------------------------------------------------------------------------------
act.ShouldThrow<XunitException>()
    .WithMessage("*John*");
```

**Comment by dennisdoomen** [comment] 2017-12-29 13:49
Unless we inject the `because` string as the last step in building the failure message, right?

**Comment by jnyrup** [comment] 2017-12-29 21:10
@dennisdoomen If that was to me, I don't quite follow.

The original problem presented in this issue arises in 
`WithMessage -> MessageBuilder.Build -> SubstituteContextualTags` when `{{empty}}` is substituted with `{}`. I believe https://github.com/fluentassertions/fluentassertions/pull/705/files#diff-96c7778de38fa36d89c9f543099daf69R74 will fix that.

The other exception arises when `because` provided to e.g. `BeNull -> BecauseOf` is an invalid format string. 
That can be resolved by either:

* manually escaping the braces if it should be a part of `because` or,
* put `{0}` in `because` and pass in the problematic string as `becauseArgs`.

**Comment by dennisdoomen** [comment] 2017-12-30 07:26
I _think_ the first problem is solved by my PR. I now ignore placeholders with double braces.

The second problem can be solved by ensuring the placeholder replacement logic runs before we replace the reason.

**Closed** 2018-01-02 16:57 UTC
Labels: bug, requires-clarification
