### ISSUE TITLE
Idea suggestion / ShouldBeEquivalentTo for nested collection's member

### ISSUE THREAD

**Issue by jesuissur** [fluentassertions/fluentassertions#242] opened 2015-03-03 16:19 UTC
Hi

Hey, first of all, great job with the 3.3 relase.  The ShouldBeEquivalentTo is much more effective.
What about having something like that to ignore nested collection's member:

```
orderDto.ShouldBeEquivalentTo(order, options => options.Excluding(o => o.Products.Without(children => children.Status))); 
```

Where Without would be an extension on Enumerable or something like that.  The goal would be to ignore member from every collection item instead of having an Excluding condition for every possible index.

Thanks
Phil

**Comment by dennisdoomen** [comment] 2015-03-12 19:37
Nice idea. But that would mean I'll be polluting the namespace with an extension method on any `IEnumerable<T>`.

**Comment by jesuissur** [comment] 2015-03-12 20:39
You're right.  Not the best way to do it.
What about a chain where you have to set the nested member after the Excluding

    orderDto.ShouldBeEquivalentTo(order, options => options.ExcludingCollectionMember(o => o.Products).For(product => product.Status))); 

Thanks
Phil

**Comment by dennisdoomen** [comment] 2015-03-12 21:04
Yeah, would be possible. But I'd have to investigate the API a bit more. It should be as natural as possible.

**Comment by dennisdoomen** [comment] 2022-03-19 08:23
Duplicate of #1771

**Closed by dennisdoomen** 2022-03-19 08:23 UTC
Labels: enhancement
